# Generated by Django 2.1.15 on 2020-04-07 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftAssignmentPivoted_by_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkSection', models.IntegerField(default=0, verbose_name='واحد')),
                ('YearWorkingPeriod', models.IntegerField(default=0, verbose_name='سال-دوره')),
                ('Cost', models.DecimalField(decimal_places=10, default=0, max_digits=19, verbose_name='هزینه')),
                ('Rank', models.IntegerField(default=0, verbose_name='رتبه')),
                ('PersonnelBaseId', models.IntegerField(default=0, verbose_name='پرسنل')),
                ('FullName', models.IntegerField(default=0, verbose_name='تام پرسنل')),
                ('PersonnelTypes_id', models.IntegerField(default=0, verbose_name='نوع شیفت')),
                ('D01', models.IntegerField(default=0, verbose_name='ر01')),
                ('D02', models.IntegerField(default=0, verbose_name='ر02')),
                ('D03', models.IntegerField(default=0, verbose_name='ر03')),
                ('D04', models.IntegerField(default=0, verbose_name='ر04')),
                ('D05', models.IntegerField(default=0, verbose_name='ر05')),
                ('D06', models.IntegerField(default=0, verbose_name='ر06')),
                ('D07', models.IntegerField(default=0, verbose_name='ر07')),
                ('D08', models.IntegerField(default=0, verbose_name='ر08')),
                ('D09', models.IntegerField(default=0, verbose_name='ر09')),
                ('D10', models.IntegerField(default=0, verbose_name='ر10')),
                ('D11', models.IntegerField(default=0, verbose_name='ر11')),
                ('D12', models.IntegerField(default=0, verbose_name='ر12')),
                ('D13', models.IntegerField(default=0, verbose_name='ر13')),
                ('D14', models.IntegerField(default=0, verbose_name='ر14')),
                ('D15', models.IntegerField(default=0, verbose_name='ر15')),
                ('D16', models.IntegerField(default=0, verbose_name='ر16')),
                ('D17', models.IntegerField(default=0, verbose_name='ر17')),
                ('D18', models.IntegerField(default=0, verbose_name='ر18')),
                ('D19', models.IntegerField(default=0, verbose_name='ر19')),
                ('D20', models.IntegerField(default=0, verbose_name='ر20')),
                ('D21', models.IntegerField(default=0, verbose_name='ر21')),
                ('D22', models.IntegerField(default=0, verbose_name='ر22')),
                ('D23', models.IntegerField(default=0, verbose_name='ر23')),
                ('D24', models.IntegerField(default=0, verbose_name='ر24')),
                ('D25', models.IntegerField(default=0, verbose_name='ر25')),
                ('D26', models.IntegerField(default=0, verbose_name='ر26')),
                ('D27', models.IntegerField(default=0, verbose_name='ر27')),
                ('D28', models.IntegerField(default=0, verbose_name='ر28')),
                ('D29', models.IntegerField(default=0, verbose_name='ر29')),
                ('D30', models.IntegerField(default=0, verbose_name='ر30')),
                ('D31', models.IntegerField(default=0, verbose_name='ر31')),
            ],
            options={
                'verbose_name_plural': 'شیفت اختصاص داده شده',
                'db_table': 'ShiftAssignmentPivoted',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dim_Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PersianDate', models.CharField(max_length=10)),
                ('SpecialDay', models.IntegerField()),
                ('PersianYear', models.IntegerField()),
                ('PersianYearTitle', models.CharField(max_length=20)),
                ('FiscalYear', models.IntegerField()),
                ('WorkingPeriodYear', models.IntegerField()),
                ('WorkingPeriod', models.IntegerField()),
                ('WorkingPeriodTitle', models.CharField(max_length=20)),
                ('PersianSemester', models.FloatField()),
                ('PersianSemesterTitle', models.CharField(max_length=20)),
                ('PersianQuarter', models.FloatField()),
                ('PersianQuarterTitle', models.CharField(max_length=20)),
                ('PersianMonth', models.FloatField()),
                ('PersianMonthTitle', models.CharField(max_length=20)),
                ('PersianWeekNumberOfYear', models.FloatField()),
                ('PersianWeekNumberOfMonth', models.FloatField()),
                ('PersianDayOfMonth', models.FloatField()),
                ('PersianDayOfYear', models.FloatField()),
                ('PersianWeekDay', models.FloatField()),
                ('PersianWeekDayTitle', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Date',
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PersonnelBaseId', models.IntegerField(verbose_name='PersonnelBaseId in Chargoon')),
                ('FullName', models.CharField(max_length=100)),
                ('YearWorkingPeriod', models.IntegerField()),
                ('RequirementWorkMins_esti', models.IntegerField()),
                ('RequirementWorkMins_real', models.IntegerField()),
                ('EfficiencyRolePoint', models.IntegerField()),
                ('DiffNorm', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Personnel',
            },
        ),
        migrations.CreateModel(
            name='PersonnelRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YearWorkingPeriod', models.IntegerField()),
                ('Day', models.IntegerField()),
                ('Value', models.IntegerField()),
                ('Personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nip.Personnel')),
            ],
            options={
                'verbose_name_plural': 'Personnel Request',
            },
        ),
        migrations.CreateModel(
            name='PersonnelShiftDateAssignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PersonnelBaseID', models.IntegerField(null=True)),
                ('Shift', models.IntegerField(null=True)),
                ('YearWorkingPeriod', models.IntegerField()),
                ('Day', models.IntegerField()),
                ('Rank', models.IntegerField()),
                ('Cost', models.FloatField()),
                ('EndTime', models.IntegerField(null=True)),
                ('UsedParentCount', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Shift Assigned',
            },
        ),
        migrations.CreateModel(
            name='PersonnelTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=5)),
                ('Title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Personnel Type',
            },
        ),
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.IntegerField()),
                ('Title', models.CharField(max_length=100)),
                ('Length', models.IntegerField()),
                ('StartTime', models.IntegerField()),
                ('EndTime', models.IntegerField()),
                ('Type', models.CharField(blank=True, max_length=3, null=True, verbose_name='Shift Type Code')),
            ],
            options={
                'verbose_name_plural': 'Shifts',
            },
        ),
        migrations.CreateModel(
            name='ShiftTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=5)),
                ('Title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Shift Types',
            },
        ),
        migrations.CreateModel(
            name='tkp_Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Login', models.IntegerField()),
                ('Logout', models.IntegerField()),
                ('DayDisposition', models.IntegerField()),
                ('YearWorkingPeriodId', models.IntegerField()),
                ('LoginDayDisposition', models.IntegerField()),
                ('Personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nip.Personnel')),
            ],
            options={
                'verbose_name_plural': 'Time Logs',
            },
        ),
        migrations.CreateModel(
            name='WorkSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=5)),
                ('Title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'WorkSection',
            },
        ),
        migrations.CreateModel(
            name='WorkSectionRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField()),
                ('Month', models.IntegerField()),
                ('DayType', models.IntegerField()),
                ('ReqMinCount', models.IntegerField()),
                ('ReqMaxCount', models.IntegerField()),
                ('day_diff_typ', models.IntegerField(blank=True, null=True)),
                ('Date', models.IntegerField(blank=True, null=True)),
                ('PersonnelTypeReqCount', models.IntegerField(blank=True, null=True)),
                ('PersonnelTypeReq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nip.PersonnelTypes')),
                ('ShiftType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nip.ShiftTypes')),
                ('WorkSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nip.WorkSection')),
            ],
            options={
                'verbose_name_plural': 'WorkSection Requirements',
            },
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='WorkSection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nip.WorkSection'),
        ),
        migrations.AddField(
            model_name='personnelrequest',
            name='ShiftType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nip.ShiftTypes'),
        ),
        migrations.AddField(
            model_name='personnelrequest',
            name='WorkSection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nip.WorkSection'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='PersonnelTypes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nip.PersonnelTypes'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='WorkSection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nip.WorkSection'),
        ),
    ]
