# Generated by Django 2.1.15 on 2020-02-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftAssignmentPivoted_by_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkSectionId', models.IntegerField(default=0, verbose_name='واحد')),
                ('YearWorkingPeriod', models.IntegerField(default=0, verbose_name='سال-دوره')),
                ('Cost', models.DecimalField(decimal_places=10, default=0, max_digits=19, verbose_name='هزینه')),
                ('Rank', models.IntegerField(default=0, verbose_name='رتبه')),
                ('PersonnelBaseId', models.IntegerField(default=0, verbose_name='پرسنل')),
                ('FullName', models.IntegerField(default=0, verbose_name='تام پرسنل')),
                ('TypeId', models.IntegerField(default=0, verbose_name='نوع شیفت')),
                ('D01', models.IntegerField(default=0, verbose_name='ر01')),
                ('D02', models.IntegerField(default=0, verbose_name='ر02')),
                ('D03', models.IntegerField(default=0, verbose_name='ر03')),
                ('D04', models.IntegerField(default=0, verbose_name='ر04')),
                ('D05', models.IntegerField(default=0, verbose_name='ر05')),
                ('D06', models.IntegerField(default=0, verbose_name='ر06')),
                ('D07', models.IntegerField(default=0, verbose_name='ر07')),
                ('D08', models.IntegerField(default=0, verbose_name='ر08')),
                ('D09', models.IntegerField(default=0, verbose_name='ر09')),
                ('D10', models.IntegerField(default=0, verbose_name='ر10')),
                ('D11', models.IntegerField(default=0, verbose_name='ر11')),
                ('D12', models.IntegerField(default=0, verbose_name='ر12')),
                ('D13', models.IntegerField(default=0, verbose_name='ر13')),
                ('D14', models.IntegerField(default=0, verbose_name='ر14')),
                ('D15', models.IntegerField(default=0, verbose_name='ر15')),
                ('D16', models.IntegerField(default=0, verbose_name='ر16')),
                ('D17', models.IntegerField(default=0, verbose_name='ر17')),
                ('D18', models.IntegerField(default=0, verbose_name='ر18')),
                ('D19', models.IntegerField(default=0, verbose_name='ر19')),
                ('D20', models.IntegerField(default=0, verbose_name='ر20')),
                ('D21', models.IntegerField(default=0, verbose_name='ر21')),
                ('D22', models.IntegerField(default=0, verbose_name='ر22')),
                ('D23', models.IntegerField(default=0, verbose_name='ر23')),
                ('D24', models.IntegerField(default=0, verbose_name='ر24')),
                ('D25', models.IntegerField(default=0, verbose_name='ر25')),
                ('D26', models.IntegerField(default=0, verbose_name='ر26')),
                ('D27', models.IntegerField(default=0, verbose_name='ر27')),
                ('D28', models.IntegerField(default=0, verbose_name='ر28')),
                ('D29', models.IntegerField(default=0, verbose_name='ر29')),
                ('D30', models.IntegerField(default=0, verbose_name='ر30')),
                ('D31', models.IntegerField(default=0, verbose_name='ر31')),
            ],
            options={
                'verbose_name_plural': 'شیفت اختصاص داده شده',
                'db_table': '[VW].[ShiftAssignmentPivoted]',
                'managed': False,
            },
        ),
    ]
